# factor_config.yaml
# 因子计算配置文件
# 版本: 1.0
# 作者: liaoyuyang
# 描述: 不同频率级别的因子计算配置

symbol: "default"

FAC:
  min_min_fac:
    save_path: ""
    description: "分钟级别的因子计算"
    fac_func_lst:
      - "ASI"
      - "BOLLING"
      - "MAdiff_Vol_div"
      - "drawback"
      - "PVcorr"
      # - "term_rtn"
      - "KnifeReversal"
      - "IntradayEntropy"
      - "CapitalEfficiency"
      - "BuzzResonance"
      - "QST"
      - "AR"
      - "CMFmin"
      - "VRSI"
      - "KVO"
      - "DDI"
      - "PV_corr_std"
      - "TS"
      - "VHF"
      - "RPP_5D"
      - "RPP_22D"
      - "RPP_4H"
      - "RPP_2H"
      - "RPP_30M"
      - "RPP_10M"
      - "RPP_5M"
      - "RPP_3M"
      # - "ptvol5"
      # - "JC1D"
      # - "JC2H"
      - "XSMOM1M"
      - "CCI"
      - "HP"
      # - "ZCpriceinterval"
      - "SNR"
      - "dOI"
      - "RSImin"
      - "CR"
      - "CV"
      - "LR"
      - "signmom"
      - "VR"
      - "Chande"
      - "masign"
      - "ATR"
      - "skew"
      - "trendstrength"
      - "kurt"
      - "ACD"
      - "up_shadow_5mean"
      - "down_shadow_5mean"
      - "up_shadow_5std"
      - "down_shadow_5std"
      - "day_jump"
      - "day_first3power"
      # - "day_first6power"
      # - "day_first10power"
      - "day_first10colarrate"
      - "day_first10rev"
      - "day_first4redcorr"
      - "day_first4greencorr"
      - "zigzag"
      - "volatility_rg"
      - "before_bot_price_diff"
      - "bar3_trend_corr"
      - "bar5_trend_corr"

  tick_min_fac:
    save_path: ""
    description: "Tick数据聚合到分钟级别的因子"
    fac_func_lst:
      - "buy_trend"
      - "buy_trend1"
      - "buy_trend_rol10"
      - "lastprice_bias1"
      - "tickvol10"
      - "tickvol20"
      - "TMB"
      - "inflectionpoint"
      - "inflectionpoint5"

  tick_tick_fac:
    save_path: ""
    description: "原始Tick级别的因子计算"
    modifiers:
      - "MADmean"
      - "Mstdwap"
      - "TrendRevmean"
      - "Volraiseap"
      - "askdommean"
      - "biddommean"
      - "corrAskwap"
      - "corrBidwap"
      - "downmean"
      - "first"
      - "kurtosis"
      - "last"
      - "max"
      - "mean"
      - "min"
      - "skewness"
      - "std"
      - "upmean"
      - "vwap"
    
    fac_func_lst:
      - "atr"
      - "RVar"
      - "RSkew"
      - "RKurt"
      - "RVar_down_rate"
      - "ask1_vmean_20"
      - "ask2_vmean_20"
      - "ask3_vmean_20"
      - "ask4_vmean_20"
      - "ask5_vmean_20"
      - "bid1_vmean_20"
      - "bid2_vmean_20"
      - "bid3_vmean_20"
      - "bid4_vmean_20"
      - "bid5_vmean_20"
      - "sub_a1b1_vmean_20"
      - "sub_a2b2_vmean_20"
      - "sub_a3b3_vmean_20"
      - "sub_a4b4_vmean_20"
      - "sub_a5b5_vmean_20"
      - "money_flow_power"
      - "MPC"
      - "MPB"
      - "PVcorrsub_a1b1"
      - "PVcorrsub_a2b2"
      - "PVcorrsub_a3b3"
      - "PVcorrsub_a4b4"
      - "PVcorrsub_a5b5"
      - "ask_amount_sub20"
      - "bid_amount_sub20"
      - "ADTMMA"
      - "RSJ"
      - "VOI"
      - "DBCD"
      - "OIR"
      - "SOIR"
      - "MOFI"
      - "PIR"
      - "MAX"
      - "MLQSweight"
      # - "LCVOL_B"
      # - "LCVOL_A"
      # - "RTNOVERNIGHT"
      - "MCIA"
      - "MCIB"
      - "CORR_PVOL_RET"
      - "RTN_JUMP"
      - "NR"
      - "STREN"
      - "SPREAD"
      - "ASKDEPTH"
      - "BBI"
      - "resiliency"
      - "BIDDEPTH"
      - "AVGDEPTH"
      - "VOL_FLU"
      - "QUA"
      - "shortQUA"
      - "midQUA"
      - "PRICE_PRESSURE"
      - "ORDER_SLOPE_A"
      - "ORDER_SLOPE_B"
      - "PRICE_STD_B"
      - "PRICE_STD_A"
      - "OI_CHG"
      - "OI_GP_CH"
      - "OI_V_DIV"
      - "Imbalance_OI"
      - "Depth_OI_Pressure"
      - "VWAP_Deviation"
      - "OI_Price_Accel"
      - "OFI1"
      - "OFI2"
      - "OFI3"
      - "OFI4"
      - "OFI5"
      - "ILLIQ"
      - "ADTM"
      - "Hurst"
      - "Bolling"
      - "RSI"
      - "MACD"
      - "Price_Divergence"
      - "Momentum_Decay"
      - "Depth_Reversal"
      - "PRICE_VOL_CORR_A"
      - "PRICE_VOL_CORR_B"
      - "KDJ"
      - "MFI"
      - "fibonacci_retracement"
      - "LVC"
      - "tsi"
      - "CMF"
      - "RUSHSTOPASK"
      - "RUSHSTOPBID"